### ISSUE TITLE
Update rpm unable to prepare oxIdP

### ISSUE THREAD

**Issue by mzico** [GluuFederation/ceUpgrade#1]
- Tested rpm: http://repo.gluu.org/centos/testing/gluu-update24-2.4.1-1.el6.noarch.rpm
- Problem: Ldap data connector in attribute-resolver.xml fail to connect ldap:1636 or ldap:1389 after service restart / server reboot
- How to reproduce the problem: 
  - Update 2.4.0 to 2.4.1 with above rpm
  - Either restart tomcat / reboot VM 
- Sample stack trace: http://pastebin.com/5b7Qq9Wp
- Suspected configurations: 'attribute-resolver.xml' between 2.4.0 and 2.4.1

**Comment by zamilskhan** [comment]
Should this issue be open?

**Comment by adrian-gluu** [comment]
gluu-update is on pause for the moment, leave it close

**Comment by mzico** [comment]
Closing it, we are following a different approach to upgrade Gluu Server now.
