### ISSUE TITLE
2.4.3 to 2.4.4 Upgrade/Migration

### ISSUE THREAD

**Issue by mindofthecurious** [GluuFederation/ceUpgrade#5]
Upgrading from 2.4.3 to 2.4.4, the documentation states to export the data in the current Gluu version 2.4.3 and import it into the new Gluu Server instance 2.4.4. The issue is, we have existing data, Users created/stored in Gluu 2.4.3 (OpenDJ), along with openID connectors set up for SSO. Will this all be migrated across in 'export' 'import' functionality that is mentioned in the documentation or will additional steps need to be taken?

What exactly does the 'import' and 'export' functionality import/export?

**Comment by mzico** [comment]
@mindofthecurious : Please create ticket for any kind of support issue in our Support Portal ( https://support.gluu.org ).
